name: cyber_pos
description: "Cyber POS - A Flutter point of sale application."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  
  # Localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # Local storage for preferences
  shared_preferences: ^2.2.2
  

  flutter_secure_storage: ^9.0.0
  
  # Analytics and monitoring (temporarily removed)
  # firebase_core: ^2.24.2
  # firebase_analytics: ^10.7.4
  # firebase_crashlytics: ^3.4.9
  # firebase_performance: ^0.9.3+7
  
  # Ethiopian calendar support
  abushakir: ^1.0.0
  
  # Audio recording and playback
  # record: ^4.4.4  # Temporarily disabled - compatibility issues with AGP 8.1.4
  # audioplayers: ^6.0.0  # Removed - not currently used, causing deprecated API warnings
  
  # File and path management
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Permissions
  permission_handler: ^11.3.0
  
  # File handling
  mime: ^2.0.0
  
  # HTTP client
  dio: ^5.4.0
  
  # Code generation for immutable classes
  json_annotation: ^4.9.0
  
  # Functional programming with Either types
  dartz: ^0.10.1
  
  # UUID generation
  uuid: ^4.2.1
  
  # Logging
  logger: ^2.0.2+1
  
  # Loading indicators
  flutter_spinkit: ^5.2.0
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  
  # Toast notifications
  another_flushbar: ^1.12.30
  go_router: ^16.2.5
  freezed_annotation: ^3.1.0
  
  # Professional OTP input with copy-paste support
  pinput: ^6.0.0

  # Cached network images
  cached_network_image: ^3.3.1
  
  # Image picker
  image_picker: ^1.0.7
  
  # Full-screen image viewer with zoom and pan
  photo_view: ^0.14.0

  # Local database (Isar)
  isar_community: ^3.3.0
  isar_community_flutter_libs: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  riverpod_lint: ^3.0.3
  riverpod_generator: ^3.0.3
  custom_lint: ^0.8.0
  build_runner: ^2.7.1
  isar_community_generator: ^3.3.0

# Dependency overrides to match working project configuration
# sqflite_android 2.4.0 doesn't have Android 15 API dependencies (BAKLAVA)
# which require compileSdk 35, avoiding build errors
dependency_overrides:
  sqflite_android: 2.4.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # Enable code generation for localization
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logo/

  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
